name = "pascalhexagon"
version = "0.1.0"
defaultTargets = ["PascalHexagon"]

[leanOptions]
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "PascalHexagon"
