import PascalHexagon.Defs
import PascalHexagon.StandardConic
import PascalHexagon.Bracket
import PascalHexagon.Veronese
import PascalHexagon.Conic
import PascalHexagon.Projective
import PascalHexagon.Correctness
